### ISSUE TITLE
Retract while combing plugin

### ISSUE THREAD

**Issue by billbrown1951** [Dim3nsioneer/Cura-Plugins#10]
I am unable to paste the plugin into my Cura> plugin folder. When I go to my plugin folder for Cura, there is no option to paste in the drop down menu. What is the preferred way to get the .py file into that folder?

**Comment by Dim3nsioneer** [comment]
Which OS?
You might need administrator privileges.

**Comment by billbrown1951** [comment]
I have Windows 7 64bit OS. This is only a private home computer, not hooked
up to any network.

**Comment by billbrown1951** [comment]
I figured out how to get your plugin to work. I had to copy to notepad, and
save it as .py. Then I was able to place into Cura>plugin folder. Thank you

Bill Brown.

**Comment by Dim3nsioneer** [comment]
Great. For everybody else: There is a description of the installation process at the documentation which you can find at the Wiki.
