### ISSUE TITLE
TweakAtZ not working when "cool head lift" enabled

### ISSUE THREAD

**Issue by luisonoff** [Dim3nsioneer/Cura-Plugins#11]
I have checked and rechecked that the plugin is not working if I enable the "cool head lift" option.
I am using windows 8.1 and Cura 15.04.

Taking a look at the gcode, when the option is enabled, there is not a line from tweakatz, apart from the header one that says how many instances.

I will take a look at the python file, but it's my first time looking at a cura plugin.

**Comment by luisonoff** [comment]
BTW, there is something wrong with progress bar not finishing, stays fully loaded but doesnt close so Cura does not show estimated time.
Don't know if this is a Cura problem or plugin problem, thats why I didnt open a new issue.

[OFFTOPIC] Is there any reason why no one uses the head lift option? This bug should have appeared a long time ago I guess :\ [END]

**Comment by luisonoff** [comment]
Update
After looking at the code I realise the plugin is automatically deactiviting itself in any cool head lift is detected. Comments say it is this way to fix an earlier bug...  
I guess this is due to the extruder moving in Z axis while going to wait. Gonna try some temporary fixes.

**Comment by luisonoff** [comment]
I think I fixed it, but not sure yet. It works for me but should be tested in case I introduced other bugs.
I just added a new IF when a new layer is detected. Somebody can test this and maybe fix it in the official version?

(Sorry, first time using Github and still don't know how all this works)

``` python
if ';Small layer' in line: #checks for begin of Cool Head Lift
            old['state'] = state
            state = 0   
        #if ('G4' in line) and old['state'] > -1:
        #old['state'] = -1
        if ';LAYER:' in line: #new layer no. found
            if state == 0:
                state = old['state']
            layer = getValue(line, ';LAYER:', layer)
            if targetL_i > -100000: #target selected by layer no.
                if state == 2 and layer >= targetL_i: #determine targetZ from layer no.
                    targetZ = z + 0.001
```

**Comment by luisonoff** [comment]
Also, in order to check it further I would need to know why was it deactivated once, I mean, what bug was it causing?

**Comment by Dim3nsioneer** [comment]
Yes, there seems to be something wrong together with the cold head lift. However, if and when I fix it I cannot say. It depends on how fast we get a postprocessing interface for the new Cura. It is planned to have the TweakAtZ there too and this issue will certainly taken care of for the new development.
About the display of the progress bar: I saw that myself. It's something in Cura but hard to find as it sometimes works and sometimes it doesn't. As the legacy Cura has a limited lifetime left it's not on top of the priority list.

**Comment by luisonoff** [comment]
I believe my change fixes it. I did also "fix" the option to make changes at layer 0.
I know it should be better to do this changes at Cura, but for example Cura does not let me change flow at first layer, so I need this tweak.

I have been testing it for a while, but should be further tested.
I will try to upload my python file so you or somebody can check changes and decide if they should be added to the official version.

BTW, where can I get that new Cura version you are talking about?

**Comment by Dim3nsioneer** [comment]
The new Cura will be released in July. It's currently in beta testing.
I see a problem with your 'fix'. Indention seems to be wrong. Most probably the correct fix is to uncomment the two lines which are commented out. But this has to be checked first. As I mentioned before, it's not on top of the priority list.
There is actually no 'official' version. I've been supervising and driving the development for about one year until now. You are of course free to fork it from either this repo or from daid/Cura or to issue a pull request to the latter.
