### ISSUE TITLE
Retract while combing, crazy heatbed

### ISSUE THREAD

**Issue by an-tech** [Dim3nsioneer/Cura-Plugins#12]
At the end of the print, heatbed began to go up and destroyed the print and the Airwolf printer nearly.
Is it due to the "G0 Z0.00; added by RetractWhileCombing V15.02" line?
The "first and last layer only" selected, without layers or mm range. Previously it worked well.
It seems that the plugin had gone too far in the code. Now I have v15.06 but I will check gcodes for a while :)

End of gcode:

;Small layer, adding delay of 13.670756
G1 F2700 E1657.56638
G1 Z66.950
G1 F2400 E-4.50000; added by RetractWhileCombing V15.02
G0 Z0.50; added by RetractWhileCombing V15.02
G0 F7500 X153.478 Y90.275 Z69.700
G0 X173.478 Y90.275
G4 P13670
G0 X173.478 Y90.275 Z71.697
;End GCode
M104 T0 S0                     ;extruder heater off
M104 T1 S0                     ;extruder heater off
M140 S0                     ;heated bed heater off (if you have it)
G91                                    ;relative positioning
**G0 Z0.00; added by RetractWhileCombing V15.02**
G1 F2400 E0.00000; added by RetractWhileCombing V15.02
G1 F300; added by RetractWhileCombing V15.02
G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
G1 Z+0.5 E-5 X-20 Y-20 F7500 ;move Z up a bit and retract filament even more
G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way
M84                         ;steppers off
G90                         ;absolute positioning
M107                             ;fan off

![20150611_120211](https://cloud.githubusercontent.com/assets/12802795/8104943/05adcb78-1035-11e5-8c0e-3563ff2d18c1.jpg)

**Comment by Dim3nsioneer** [comment]
I could not reproduce the effect with Cura 15.04 and RetractWhileCombing 15.06. I assume you use RepRap (Marlin/Sprinter) flavor? Can you please post the RWC-settings and your plain end.gcode?

**Comment by an-tech** [comment]
Yes RepRap (Marlin/Sprinter). I just recreated the process and have the same results with v15.06 plugin and Cura 15.04. Error occurs when cool head lift option is enabled and object (like sphere with about 15mm r) have on the top layer small area.

![error2](https://cloud.githubusercontent.com/assets/12802795/8117563/5e2baf14-1089-11e5-8dca-2feafa881ee7.PNG)

It happens also with standard end code and mostly standard cura settings (i have it up to date now, and change only cool head lift and some plugin settings)

> ;End GCode
> M104 S0                     ;extruder heater off
> M140 S0                     ;heated bed heater off (if you have it)
> G91                                    ;relative positioning
> G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
> G1 Z+0.5 E-5 X-20 Y-20 F{travel_speed} ;move Z up a bit and retract filament even more
> G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way
> M84                         ;steppers off
> G90                         ;absolute positioning
> ;{profile_string}

I don't know what is RWC-settings so I paste profile settings, hope you mean that.

> [profile]
> layer_height = 0.2
> wall_thickness = 0.8
> retraction_enable = True
> solid_layer_thickness = 0.6
> fill_density = 20
> nozzle_size = 0.4
> print_speed = 50
> print_temperature = 210
> print_temperature2 = 0
> print_temperature3 = 0
> print_temperature4 = 0
> print_temperature5 = 0
> print_bed_temperature = 70
> support = None
> platform_adhesion = None
> support_dual_extrusion = Both
> wipe_tower = False
> wipe_tower_volume = 15
> ooze_shield = False
> filament_diameter = 2.85
> filament_diameter2 = 0
> filament_diameter3 = 0
> filament_diameter4 = 0
> filament_diameter5 = 0
> filament_flow = 100.0
> retraction_speed = 40.0
> retraction_amount = 4.5
> retraction_dual_amount = 16.5
> retraction_min_travel = 1.5
> retraction_combing = All
> retraction_minimal_extrusion = 0.02
> retraction_hop = 0.0
> bottom_thickness = 0.3
> layer0_width_factor = 100
> object_sink = 0.0
> overlap_dual = 0.15
> travel_speed = 150.0
> bottom_layer_speed = 20
> infill_speed = 0.0
> solidarea_speed = 0.0
> inset0_speed = 0.0
> insetx_speed = 0.0
> cool_min_layer_time = 5
> fan_enabled = True
> skirt_line_count = 1
> skirt_gap = 3.0
> skirt_minimal_length = 150.0
> fan_full_height = 0.5
> fan_speed = 100
> fan_speed_max = 100
> cool_min_feedrate = 10
> cool_head_lift = True
> solid_top = True
> solid_bottom = True
> fill_overlap = 15
> perimeter_before_infill = False
> support_type = Lines
> support_angle = 60
> support_fill_rate = 15
> support_xy_distance = 0.7
> support_z_distance = 0.15
> spiralize = False
> simple_mode = False
> brim_line_count = 20
> raft_margin = 5.0
> raft_line_spacing = 3.0
> raft_base_thickness = 0.3
> raft_base_linewidth = 1.0
> raft_interface_thickness = 0.27
> raft_interface_linewidth = 0.4
> raft_airgap_all = 0.0
> raft_airgap = 0.22
> raft_surface_layers = 2
> raft_surface_thickness = 0.27
> raft_surface_linewidth = 0.4
> fix_horrible_union_all_type_a = True
> fix_horrible_union_all_type_b = False
> fix_horrible_use_open_bits = False
> fix_horrible_extensive_stitching = False
> plugin_config = (lp1
>     (dp2
>     S'params'
>     p3
>     (dp4
>     S'maxZ'
>     p5
>     V
>     sS'minL'
>     p6
>     V
>     sS'FirstLast'
>     p7
>     I1
>     sS'retractdistance'
>     p8
>     V4.5
>     p9
>     sS'minZ'
>     p10
>     V
>     sS'lift'
>     p11
>     V0.25
>     p12
>     sS'maxL'
>     p13
>     V
>     sS'minDist'
>     p14
>     V2.0
>     p15
>     sS'speed'
>     p16
>     V30
>     p17
>     ssS'filename'
>     p18
>     S'RetractWhileCombing.py'
>     p19
>     sa.
> object_center_x = -1
> object_center_y = -1
> [alterations]
> start.gcode = ;Sliced at: {day} {date} {time}
>     ;Basic settings: Layer height: {layer_height} Walls: {wall_thickness} Fill: {fill_density}
>     ;Print time: {print_time}
>     ;Filament used: {filament_amount}m {filament_weight}g
>     ;Filament cost: {filament_cost}
>     ;M190 S{print_bed_temperature} ;Uncomment to add your own bed temperature line
>     ;M109 S{print_temperature} ;Uncomment to add your own temperature line
>     G21        ;metric values
>     G90        ;absolute positioning
>     M82        ;set extruder to absolute mode
>     M107       ;start with the fan off
>     G28 X0 Y0  ;move X/Y to min endstops
>     G28 Z0     ;move Z to min endstops
>     G1 Z15.0 F{travel_speed} ;move the platform down 15mm
>     G92 E0                  ;zero the extruded length
>     G1 F200 E3              ;extrude 3mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F{travel_speed}
>     ;Put printing message on LCD screen
>     M117 Printing...
> end.gcode = ;End GCode
>     M104 S0                     ;extruder heater off
>     M140 S0                     ;heated bed heater off (if you have it)
>     G91                                    ;relative positioning
>     G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
>     G1 Z+0.5 E-5 X-20 Y-20 F{travel_speed} ;move Z up a bit and retract filament even more
>     G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way
>     M84                         ;steppers off
>     G90                         ;absolute positioning
>     ;{profile_string}
> start2.gcode = ;Sliced at: {day} {date} {time}
>     ;Basic settings: Layer height: {layer_height} Walls: {wall_thickness} Fill: {fill_density}
>     ;Print time: {print_time}
>     ;Filament used: {filament_amount}m {filament_weight}g
>     ;Filament cost: {filament_cost}
>     ;M190 S{print_bed_temperature} ;Uncomment to add your own bed temperature line
>     ;M104 S{print_temperature} ;Uncomment to add your own temperature line
>     ;M109 T1 S{print_temperature2} ;Uncomment to add your own temperature line
>     ;M109 T0 S{print_temperature} ;Uncomment to add your own temperature line
>     G21        ;metric values
>     G90        ;absolute positioning
>     M107       ;start with the fan off
>     G28 X0 Y0  ;move X/Y to min endstops
>     G28 Z0     ;move Z to min endstops
>     G1 Z15.0 F{travel_speed} ;move the platform down 15mm
>     T1                      ;Switch to the 2nd extruder
>     G92 E0                  ;zero the extruded length
>     G1 F200 E10             ;extrude 10mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F200 E-{retraction_dual_amount}
>     T0                      ;Switch to the first extruder
>     G92 E0                  ;zero the extruded length
>     G1 F200 E10             ;extrude 10mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F{travel_speed}
>     ;Put printing message on LCD screen
>     M117 Printing...
> end2.gcode = ;End GCode
>     M104 T0 S0                     ;extruder heater off
>     M104 T1 S0                     ;extruder heater off
>     M140 S0                     ;heated bed heater off (if you have it)
>     G91                                    ;relative positioning
>     G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
>     G1 Z+0.5 E-5 X-20 Y-20 F{travel_speed} ;move Z up a bit and retract filament even more
>     G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way
>     M84                         ;steppers off
>     G90                         ;absolute positioning
>     ;{profile_string}
> start3.gcode = ;Sliced at: {day} {date} {time}
>     ;Basic settings: Layer height: {layer_height} Walls: {wall_thickness} Fill: {fill_density}
>     ;Print time: {print_time}
>     ;Filament used: {filament_amount}m {filament_weight}g
>     ;Filament cost: {filament_cost}
>     ;M190 S{print_bed_temperature} ;Uncomment to add your own bed temperature line
>     ;M104 S{print_temperature} ;Uncomment to add your own temperature line
>     ;M109 T1 S{print_temperature2} ;Uncomment to add your own temperature line
>     ;M109 T0 S{print_temperature} ;Uncomment to add your own temperature line
>     G21        ;metric values
>     G90        ;absolute positioning
>     M107       ;start with the fan off
>     G28 X0 Y0  ;move X/Y to min endstops
>     G28 Z0     ;move Z to min endstops
>     G1 Z15.0 F{travel_speed} ;move the platform down 15mm
>     T2                      ;Switch to the 2nd extruder
>     G92 E0                  ;zero the extruded length
>     G1 F200 E10             ;extrude 10mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F200 E-{retraction_dual_amount}
>     T1                      ;Switch to the 2nd extruder
>     G92 E0                  ;zero the extruded length
>     G1 F200 E10             ;extrude 10mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F200 E-{retraction_dual_amount}
>     T0                      ;Switch to the first extruder
>     G92 E0                  ;zero the extruded length
>     G1 F200 E10             ;extrude 10mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F{travel_speed}
>     ;Put printing message on LCD screen
>     M117 Printing...
> end3.gcode = ;End GCode
>     M104 T0 S0                     ;extruder heater off
>     M104 T1 S0                     ;extruder heater off
>     M104 T2 S0                     ;extruder heater off
>     M140 S0                     ;heated bed heater off (if you have it)
>     G91                                    ;relative positioning
>     G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
>     G1 Z+0.5 E-5 X-20 Y-20 F{travel_speed} ;move Z up a bit and retract filament even more
>     G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way
>     M84                         ;steppers off
>     G90                         ;absolute positioning
>     ;{profile_string}
> start4.gcode = ;Sliced at: {day} {date} {time}
>     ;Basic settings: Layer height: {layer_height} Walls: {wall_thickness} Fill: {fill_density}
>     ;Print time: {print_time}
>     ;Filament used: {filament_amount}m {filament_weight}g
>     ;Filament cost: {filament_cost}
>     ;M190 S{print_bed_temperature} ;Uncomment to add your own bed temperature line
>     ;M104 S{print_temperature} ;Uncomment to add your own temperature line
>     ;M109 T2 S{print_temperature2} ;Uncomment to add your own temperature line
>     ;M109 T1 S{print_temperature2} ;Uncomment to add your own temperature line
>     ;M109 T0 S{print_temperature} ;Uncomment to add your own temperature line
>     G21        ;metric values
>     G90        ;absolute positioning
>     M107       ;start with the fan off
>     G28 X0 Y0  ;move X/Y to min endstops
>     G28 Z0     ;move Z to min endstops
>     G1 Z15.0 F{travel_speed} ;move the platform down 15mm
>     T3                      ;Switch to the 4th extruder
>     G92 E0                  ;zero the extruded length
>     G1 F200 E10             ;extrude 10mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F200 E-{retraction_dual_amount}
>     T2                      ;Switch to the 3th extruder
>     G92 E0                  ;zero the extruded length
>     G1 F200 E10             ;extrude 10mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F200 E-{retraction_dual_amount}
>     T1                      ;Switch to the 2nd extruder
>     G92 E0                  ;zero the extruded length
>     G1 F200 E10             ;extrude 10mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F200 E-{retraction_dual_amount}
>     T0                      ;Switch to the first extruder
>     G92 E0                  ;zero the extruded length
>     G1 F200 E10             ;extrude 10mm of feed stock
>     G92 E0                  ;zero the extruded length again
>     G1 F{travel_speed}
>     ;Put printing message on LCD screen
>     M117 Printing...
> end4.gcode = ;End GCode
>     M104 T0 S0                     ;extruder heater off
>     M104 T1 S0                     ;extruder heater off
>     M104 T2 S0                     ;extruder heater off
>     M104 T3 S0                     ;extruder heater off
>     M140 S0                     ;heated bed heater off (if you have it)
>     G91                                    ;relative positioning
>     G1 E-1 F300                            ;retract the filament a bit before lifting the nozzle, to release some of the pressure
>     G1 Z+0.5 E-5 X-20 Y-20 F{travel_speed} ;move Z up a bit and retract filament even more
>     G28 X0 Y0                              ;move X/Y to min endstops, so the head is out of the way
>     M84                         ;steppers off
>     G90                         ;absolute positioning
>     ;{profile_string}
> support_start.gcode = 
> support_end.gcode = 
> cool_start.gcode = 
> cool_end.gcode = 
> replace.csv = 
> preswitchextruder.gcode = ;Switch between the current extruder and the next extruder, when printing with multiple extruders.
>     ;This code is added before the T(n)
> postswitchextruder.gcode = ;Switch between the current extruder and the next extruder, when printing with multiple extruders.
>     ;This code is added after the T(n)

**Comment by Dim3nsioneer** [comment]
@an-tech : Finally I could reproduce the bug. As you pointed out, it is appears only if a cold head lift happens on the last layer.
I will produce a bugfix.
For the time being I recommend to use a layer selection of 'from 0 to 0' instead of the first/last option if the model has a tiny top and the cold head lift option is activated.

**Comment by Dim3nsioneer** [comment]
@an-tech Could you maybe try the new test version?

**Comment by an-tech** [comment]
@Dim3nsioneer Great work. New version seems to fix a problem completely :)

**Comment by Dim3nsioneer** [comment]
@an-tech Thank you for testing.
