### ISSUE TITLE
TweakAtZ not resetting in one-at-a-time mode

### ISSUE THREAD

**Issue by Patrick181** [Dim3nsioneer/Cura-Plugins#14]
UM2 - 15.04
Cura - 15.04
TweakAtZ  - 4.0.2

TweakAtZ is not resetting upon the next sequenced print using fans and Z height (mm).  It is possible that TweakAtZ may also fail to reset under other parameters but I have not tested them.

Associated settings are as such:
Cura - Print one-at-a-time mode: Enabled
Cura - Enable cooling fan: Unchecked
TweakAtZ Z height to tweak at (mm): 9
New Fan Speed (0-255): 100

**Comment by Dim3nsioneer** [comment]
Reset on UM2 does not work properly with settings that are influenced by Cura during print such as the fan speed. Bugfix is in progress.

**Comment by Dim3nsioneer** [comment]
Should be fixed with https://github.com/Dim3nsioneer/Cura-Plugins/commit/7804f93c9ec2c36cb53cc9456ac21d73255fef05
